<a href="https://colab.research.google.com/github/danielbau26/Aplicadas/blob/main/taller_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TALLER 2

##**Integrantes**
###Andres Martinez
###Juan Camilo Pelaez - A00411206
###Daniel Bautista - A0041481
###Veronica Flor - A00411667

In [ ]:
import numpy as np
import statistics as st

In [ ]:
#Ejercicio 1 | Hallar los números primos de una lista

def numeros_primos(lista_numeros):

  numeros_primos = []

  for x in lista_numeros:
    if x < 2:
      break

    if x >= 2:
      for i in range(2, int(x**0.5) + 1):
        if x % i == 0:
          es_primo = False
          break
        else:
          es_primo = True

      if es_primo:
        numeros_primos.append(x)

  return numeros_primos

lista_numeros = [13, 2, 6, 4, 5]

primos = numeros_primos(lista_numeros)
print("Números primos:", primos)

Números primos: [13, 2, 5]


In [ ]:
#Ejercicio 2 | Elementos comunes entre dos listas

def numeros_comunes (lista_1,lista_2):
  comunes=[]
  for i in lista_1:
      if i in lista_2 and i not in comunes:
        comunes.append(i)
  return comunes

lista_1=[1,2,3,4,5]
lista_2=[2,4,6,8,5]

print("Los elementos comunes entre las listas son:",numeros_comunes(lista_1,lista_2))

Los elementos comunes entre las listas son: [2, 4, 5]


In [ ]:
#Ejercicio 3 | convertir una lista en una matriz cuadrada y
#Si no se puede dar error

def convertir_a_matriz(lista):
  if len(lista[0]) == len(lista[1]) and len(lista[1]) == len(lista[2]):
      return np.array(lista)
  else:
    return "No se puede crear una matriz cuadrada"

lista=[[1,2,3,4],[2,3,4,5],[3,4,5,6]]

print("Matriz convertida:")
print(convertir_a_matriz(lista))

Matriz convertida:
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [ ]:
#Ejercicio 4 | Devolver la media, mediana y moda de una lista

def medidas_de_tendencia_central(lista):
  media = st.mean(lista)
  mediana = st.median(lista)
  moda = st.mode(lista)

  return media, mediana, moda

cuarta_lista=[1,2,3,4,2,2,3]

media, mediana, moda = medidas_de_tendencia_central(cuarta_lista)
print(f"La media es: {media}")
print(f"La mediana es: {mediana}")
print(f"La moda es: {moda}")

La media es: 2.4285714285714284
La mediana es: 2
La moda es: 2


In [ ]:
#Ejercicio 5 | Conocer el costo total de una compra almacenando los precios y
#Las cosas compradas en dos listas diferentes

def total(precios,compras):
  total = 0
  for i in range(len(precios)):
    total += precios[i]*compras[i]
  if total >100:
    total = total*0.9
  return total

precios=[2,3,20,50,8]
cantidades_compradas=[5,6,4,3,7]

print(f"El costo total de la compra es de: ${total(precios,cantidades_compradas)}")

El costo total de la compra es de: $282.6


In [ ]:
#Ejercicio 6 | Conocer la disponibilidad de productos despues de un día de
#Trabajo

def disponibilidad(inventario,vendidos):
  for x in vendidos:
    if x in inventario:
      inventario.remove(x)
  return inventario

inventario=["Manzana", "Pera", "Papaya", "Banano", "Arroz"]
vendidos=["Arroz", "Pera"]

print("Los productos disponibles en el inventario son:",disponibilidad(inventario,vendidos))

Los productos disponibles en el inventario son: ['Manzana', 'Papaya', 'Banano']


In [ ]:
#Ejercicio 7 | Apartir de una lista de las temperaturas de una mes conocer las
#Temperaturas mayor a 30, entre 20 y 30 y menores a 20

def temperaturas(lista):
  debajo_20=[]
  mayor_30=[]
  entre_20_30=[]
  for i in range(len(lista)):
    if lista[i] > 30:
      mayor_30.append(lista[i])
    elif (20>=lista[i]<=30):
      entre_20_30.append(lista[i])
    else:
      debajo_20.append(lista[i])
  return debajo_20, entre_20_30, mayor_30

temperaturas_diarias = [22.5, 23.0, 21.8, 20.1, 19.5, 18.0, 17.2, 21.4, 24.0, 25.3, 26.1, 27.8, 28.5, 31.0]

debajo, entre, mayor = temperaturas(temperaturas_diarias)
print(f"Temperaturas por debajo de 20: {debajo}")
print(f"Temperaturas entre 20 y 30: {entre}")
print(f"Temperaturas por encima de 30: {mayor}")

Temperaturas por debajo de 20: [22.5, 23.0, 21.8, 20.1, 21.4, 24.0, 25.3, 26.1, 27.8, 28.5]
Temperaturas entre 20 y 30: [19.5, 18.0, 17.2]
Temperaturas por encima de 30: [31.0]


In [ ]:
#Ejercicio 8 | Apartir de una lista de alimentos y calorias por alimentos
#Conocer si supera las 2000 calorias diarias

def calcular_calorias(cantidad):
    alimentos = []
    calorias = []
    calorias_total = 0

    for i in range(cantidad):
        print("----------------------------------------------------------------")
        alimento = input("Ingrese el nombre del alimento: ")
        print()
        calorias_alimento = int(input("Ingrese la cantidad de calorías del alimento: "))

        alimentos.append(alimento)
        calorias.append(calorias_alimento)
        calorias_total += calorias_alimento

    print("----------------------------------------------------------------")
    print(f"Usted ingirió {calorias_total} calorías.")

    if calorias_total > 2000:
        resultado = "Se superó las calorías recomendadas diarias."
    else:
        resultado = "No se superaron las calorías recomendadas diarias."
    return resultado

cantidad = int(input("Ingrese la cantidad de alimentos que ingirió: "))
print(calcular_calorias(cantidad))

Ingrese la cantidad de alimentos que ingirió: 5
----------------------------------------------------------------
Ingrese el nombre del alimento: pollo

Ingrese la cantidad de calorías del alimento: 500
----------------------------------------------------------------
Ingrese el nombre del alimento: carne

Ingrese la cantidad de calorías del alimento: 400
----------------------------------------------------------------
Ingrese el nombre del alimento: papa

Ingrese la cantidad de calorías del alimento: 600
----------------------------------------------------------------
Ingrese el nombre del alimento: cafe

Ingrese la cantidad de calorías del alimento: 900
----------------------------------------------------------------
Ingrese el nombre del alimento: sopa

Ingrese la cantidad de calorías del alimento: 300
----------------------------------------------------------------
Usted ingirió 2700 calorías.
Se superó las calorías recomendadas diarias.


In [ ]:
#Ejercicio 9 | A partir de las ventas del mes calcular el promedio y
#Cuantos meses superaron el promedio

def ventas(ventas):
  total_ventas = 0

  for i in range(12):
    total_ventas += ventas[i]
  promedio = total_ventas/12

  return promedio

ventas_mensuales = [0]*12

for i in range(12):
  ventas_mensuales[i] = int(input(f"Ingrese el valor de las ventas del mes {i+1}: "))

promedio_ventas = ventas(ventas_mensuales)

print("----------------------------------------------------------------")
print(f"El promedio de ventas del mes es de: {promedio_ventas:.2f}")

for i in range(12):
    if ventas_mensuales[i]>promedio_ventas:
      print("----------------------------------------------------------------")
      print(f"El mes {i+1} supero el promedio de ventas mensuales con un total de {ventas_mensuales[i]}")

Ingrese el valor de las ventas del mes 1: 3123132
Ingrese el valor de las ventas del mes 2: 231213
Ingrese el valor de las ventas del mes 3: 3453453
Ingrese el valor de las ventas del mes 4: 123124
Ingrese el valor de las ventas del mes 5: 53453456
Ingrese el valor de las ventas del mes 6: 3453453
Ingrese el valor de las ventas del mes 7: 3412321
Ingrese el valor de las ventas del mes 8: 2313123
Ingrese el valor de las ventas del mes 9: 3454353
Ingrese el valor de las ventas del mes 10: 435345
Ingrese el valor de las ventas del mes 11: 3454353
Ingrese el valor de las ventas del mes 12: 12312312
----------------------------------------------------------------
El promedio de ventas del mes es de: 7434969.83
----------------------------------------------------------------
El mes 5 supero el promedio de ventas mensuales con un total de 53453456
----------------------------------------------------------------
El mes 12 supero el promedio de ventas mensuales con un total de 12312312


In [ ]:
#Ejercicio 10 | Según el monto total se realiza un descuento:
# - 5% si el total está entre 50 y 100.
# - 10% si el total es mayor a 100 y menor a 200.
# - 15% si el total es mayor o igual a $200.

def descuentos(total):
  descuento = 0
  newtotal=total
  if 50 < total < 100:
    descuento = total * 0.05
    newtotal = total- descuento

  elif 100<= total < 200:
    descuento = total * 0.1
    newtotal = total- descuento

  elif total >= 200:
    descuento = total * 0.15
    newtotal = total- descuento

  return newtotal, descuento

total_compra = float(input("Ingrese el total de su compra: "))
print("")

new_total, descuento = descuentos(total_compra)

if descuento > 0:
  print(f"Usted obtuvo un {descuento}% de descuento y la compra le queda en: {new_total}")
else:
  print(f"No aplica descuento. Su total es: ${new_total:.2f}")

Ingrese el total de su compra: 70

Usted obtuvo un 3.5% de descuento y la compra le queda en: 66.5


In [ ]:
#Ejercicio 11 | Registro de pacientes

def registro_pacientes(nombres, edades):
    pacientes_prioritarios = [nombres[i] for i in range(len(edades)) if edades[i] > 60]
    return pacientes_prioritarios

n = int(input("Ingrese la cantidad de pacientes: "))
nombres = []
edades = []

for _ in range(n):
    nombres.append(input("Nombre del paciente: "))
    edades.append(int(input("Edad del paciente: ")))

print("Pacientes con atención prioritaria: ", registro_pacientes(nombres, edades))

Ingrese la cantidad de pacientes: 2
Nombre del paciente: jose
Edad del paciente: 55
Nombre del paciente: andres
Edad del paciente: 70
Pacientes con atención prioritaria:  ['andres']


In [ ]:
#Ejercicio 12 | Cálculo de gastos mensuales

def calculo_gastos_mensuales(gastos, categorias):
    total = np.sum(gastos)
    max_gasto = np.max(gastos)
    categoria_max = categorias[np.argmax(gastos)]
    return total, categoria_max, max_gasto

n = int(input("Ingrese la cantidad de categorías de gasto: "))
gastos = []
categorias = []

for _ in range(n):
    categorias.append(input("Nombre de la categoría: "))
    gastos.append(float(input(f"Ingrese el gasto en {categorias[-1]}: ")))

total, cat_max, max_gasto = calculo_gastos_mensuales(gastos, categorias)
print(f"Total de gastos: {total}, Mayor gasto en: {cat_max} ({max_gasto})")


Ingrese la cantidad de categorías de gasto: 3
Nombre de la categoría: arriendo
Ingrese el gasto en arriendo: 1241434
Nombre de la categoría: comida
Ingrese el gasto en comida: 143412
Nombre de la categoría: salidas
Ingrese el gasto en salidas: 143434
Total de gastos: 1528280.0, Mayor gasto en: arriendo (1241434.0)


In [ ]:
#Ejercicio 13 | Control de asistencia a eventos

def control_asistencia(registrados, asistieron):
    no_asistieron = list(set(registrados) - set(asistieron))
    return no_asistieron

n = int(input("Ingrese la cantidad de personas registradas: "))
registrados = [input("Nombre de la persona registrada: ") for _ in range(n)]

m = int(input("Ingrese la cantidad de personas que asistieron: "))
asistieron = [input("Nombre de la persona asistente: ") for _ in range(m)]

print("Personas que no asistieron:", control_asistencia(registrados, asistieron))

Ingrese la cantidad de personas registradas: 5
Nombre de la persona registrada: juan
Nombre de la persona registrada: jose
Nombre de la persona registrada: andres
Nombre de la persona registrada: carlos
Nombre de la persona registrada: kevin
Ingrese la cantidad de personas que asistieron: 4
Nombre de la persona asistente: juan
Nombre de la persona asistente: andres
Nombre de la persona asistente: carlos
Nombre de la persona asistente: kevin
Personas que no asistieron: ['jose']


In [ ]:
#Ejercicio 14 | Recomendación de ejercicio diario

def recomendacion_ejercicio(minutos_semanales):
    promedio = np.mean(minutos_semanales)
    if promedio > 60:
        return "Excelente, estás en forma"
    elif 30 <= promedio <= 60:
        return "Buen trabajo, pero puedes mejorar"
    else:
        return "Debes hacer más ejercicio"

minutos_semanales = [int(input(f"Minutos de ejercicio del día {i+1}: ")) for i in range(7)]
print("Recomendación de ejercicio:", recomendacion_ejercicio(minutos_semanales))

Minutos de ejercicio del día 1: 50
Minutos de ejercicio del día 2: 20
Minutos de ejercicio del día 3: 45
Minutos de ejercicio del día 4: 120
Minutos de ejercicio del día 5: 100
Minutos de ejercicio del día 6: 105
Minutos de ejercicio del día 7: 90
Recomendación de ejercicio: Excelente, estás en forma
